// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 06/04/2026, 07:33:34
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["E:/Vue/Nuxt/nuxt-supabase-app/nuxt-supabase-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Vue/Nuxt/nuxt-supabase-app/nuxt-supabase-app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Vue/Nuxt/nuxt-supabase-app/nuxt-supabase-app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Vue/Nuxt/nuxt-supabase-app/nuxt-supabase-app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Vue/Nuxt/nuxt-supabase-app/nuxt-supabase-app/plugins/**/*.{js,ts,mjs}","E:/Vue/Nuxt/nuxt-supabase-app/nuxt-supabase-app/composables/**/*.{js,ts,mjs}","E:/Vue/Nuxt/nuxt-supabase-app/nuxt-supabase-app/utils/**/*.{js,ts,mjs}","E:/Vue/Nuxt/nuxt-supabase-app/nuxt-supabase-app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/Vue/Nuxt/nuxt-supabase-app/nuxt-supabase-app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/Vue/Nuxt/nuxt-supabase-app/nuxt-supabase-app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/Vue/Nuxt/nuxt-supabase-app/nuxt-supabase-app/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;